<?php
// /services/api/generate_sql.php
set_time_limit(300); // 5 Dakika süre
ini_set('display_errors', 1);
error_reporting(E_ALL);
header('Content-Type: application/json; charset=utf-8');

require_once $_SERVER["DOCUMENT_ROOT"].'/config/db.php';
require_once $_SERVER["DOCUMENT_ROOT"].'/services/ai/GeminiService.php';

if (session_status() == PHP_SESSION_NONE) { session_start(); }

if (!isset($_SESSION['user_id'])) {
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit;
}

$project_id = $_POST['project_id'] ?? null;
if (!$project_id) {
    echo json_encode(['success' => false, 'message' => 'Missing ID']);
    exit;
}

try {
    // ---------------------------------------------------------
    // BÖLÜM 1: PHP İLE YAPISAL SQL (CREATE & ALTER) - KESİN DOĞRULUK
    // ---------------------------------------------------------

    // Tabloları Çek
    $stmtTables = $db->prepare("SELECT * FROM project_tables WHERE project_id = ?");
    $stmtTables->execute([$project_id]);
    $tables = $stmtTables->fetchAll(PDO::FETCH_ASSOC);

    // İlişkileri Çek
    $stmtRels = $db->prepare("SELECT * FROM project_relationships WHERE project_id = ?");
    $stmtRels->execute([$project_id]);
    $relationships = $stmtRels->fetchAll(PDO::FETCH_ASSOC);

    // Kuralları Çek (YENİ EKLENDİ)
    $stmtRules = $db->prepare("SELECT rule_id, rule_statement, rule_type FROM project_rules WHERE project_id = ?");
    $stmtRules->execute([$project_id]);
    $rules = $stmtRules->fetchAll(PDO::FETCH_ASSOC);

    // Kuralları Metne Dök
    $rulesText = "";
    foreach ($rules as $r) {
        $rulesText .= "- [{$r['rule_id']}] ({$r['rule_type']}): {$r['rule_statement']}\n";
    }

    $tableMap = [];
    foreach($tables as $t) $tableMap[$t['id']] = $t['table_name'];

    // DDL Başlangıcı
    $structureSQL = "-- =============================================\n";
    $structureSQL .= "-- PART 1: DATABASE STRUCTURE (DDL)\n";
    $structureSQL .= "-- Generated by AI Database Architect\n";
    $structureSQL .= "-- Date: " . date("Y-m-d H:i:s") . "\n";
    $structureSQL .= "-- =============================================\n\n";
    $structureSQL .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

    // Tablo Oluşturma Döngüsü
    foreach ($tables as $t) {
        $tableName = $t['table_name'];
        $structureSQL .= "-- Table: $tableName\n";
        $structureSQL .= "DROP TABLE IF EXISTS `$tableName`;\n";
        $structureSQL .= "CREATE TABLE `$tableName` (\n";

        $stmtCols = $db->prepare("SELECT * FROM project_columns WHERE table_id = ?");
        $stmtCols->execute([$t['id']]);
        $columns = $stmtCols->fetchAll(PDO::FETCH_ASSOC);

        // PK Sayısı (Auto Inc kontrolü için)
        $pkCount = 0;
        foreach ($columns as $c) { if ($c['is_primary_key']) $pkCount++; }

        $colLines = [];
        $primaryKeys = [];

        foreach ($columns as $col) {
            $line = "  `{$col['name']}` " . strtoupper($col['data_type']);

            if (!$col['is_nullable']) $line .= " NOT NULL";
            else $line .= " DEFAULT NULL";

            // Sadece tek PK varsa ve INT ise Auto Increment
            if ($col['is_primary_key'] && $pkCount === 1 && stripos($col['data_type'], 'INT') !== false) {
                $line .= " AUTO_INCREMENT";
            }

            if ($col['is_unique'] && !$col['is_primary_key']) $line .= " UNIQUE";

            $colLines[] = $line;

            if ($col['is_primary_key']) $primaryKeys[] = "`{$col['name']}`";
        }

        if (!empty($primaryKeys)) {
            $colLines[] = "  PRIMARY KEY (" . implode(", ", $primaryKeys) . ")";
        }

        $structureSQL .= implode(",\n", $colLines);
        $structureSQL .= "\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n\n";
    }

    // İlişkileri (FK) Ekle
    if (!empty($relationships)) {
        $structureSQL .= "-- Relationships (Foreign Keys)\n";
        foreach ($relationships as $rel) {
            $parentTable = $tableMap[$rel['parent_table_id']] ?? null;
            $childTable = $tableMap[$rel['child_table_id']] ?? null;

            if ($parentTable && $childTable) {
                $stmtFK = $db->prepare("SELECT name FROM project_columns WHERE table_id = ? AND is_foreign_key = 1");
                $stmtFK->execute([$rel['child_table_id']]);
                $fkCols = $stmtFK->fetchAll(PDO::FETCH_COLUMN);

                $stmtPK = $db->prepare("SELECT name FROM project_columns WHERE table_id = ? AND is_primary_key = 1");
                $stmtPK->execute([$rel['parent_table_id']]);
                $pkCol = $stmtPK->fetchColumn();

                $targetCol = null;
                foreach ($fkCols as $fkName) {
                    if (strpos($fkName, substr($parentTable, 0, -1)) !== false || $fkName === $pkCol) {
                        $targetCol = $fkName;
                        break;
                    }
                }
                if (!$targetCol && count($fkCols) > 0) $targetCol = $fkCols[0];

                if ($targetCol && $pkCol) {
                    $constraintName = "fk_" . substr($childTable, 0, 10) . "_" . substr($parentTable, 0, 10) . "_" . rand(100,999);
                    $structureSQL .= "ALTER TABLE `$childTable` ADD CONSTRAINT `$constraintName` ";
                    $structureSQL .= "FOREIGN KEY (`$targetCol`) REFERENCES `$parentTable` (`$pkCol`) ";
                    $structureSQL .= "ON DELETE CASCADE ON UPDATE CASCADE;\n";
                }
            }
        }
    }

    $structureSQL .= "\nSET FOREIGN_KEY_CHECKS = 1;\n";

    // ---------------------------------------------------------
    // BÖLÜM 2: AI İLE MANTIKSAL SQL (KURALLARA BAKARAK)
    // ---------------------------------------------------------

    $aiPrompt = "
    ROLE: Senior Database Administrator & SQL Developer.
    TASK: Generate advanced SQL components (Triggers, Views, Roles, Queries) based on the Schema AND Business Rules.

    SOURCE 1: BUSINESS RULES (Logic to Implement):
    $rulesText

    SOURCE 2: DATABASE SCHEMA (DDL Structure):
    $structureSQL

    CRITICAL INSTRUCTIONS:
    1. **Implement Rules:** If a rule says \"Stock cannot be negative\", create a CHECK constraint or TRIGGER. If a rule says \"Only Managers can delete\", create a ROLE.
    2. **TRIGGERS:** Create at least 2 triggers that enforce specific business rules found in Source 1.
    3. **VIEWS:** Create at least 2 views that simplify complex reporting requirements implied in the rules.
    4. **ROLES:** Define roles mentioned in the rules (or generic ones like 'admin', 'user') and GRANT permissions accordingly.
    5. **REPORTING QUERIES:** Write 3 complex SELECT queries (with JOINs/Aggregates) that answer business questions derived from the rules.

    OUTPUT FORMAT:
    - Return ONLY valid SQL code.
    - Use comments (-- Rule: ...) to explain which rule is being implemented.
    - Do NOT wrap in markdown blocks. Just raw SQL text.
    ";

    $aiService = new GeminiService($db);
    $advancedSQL = $aiService->callApi($aiPrompt, false);

    // Temizlik
    $advancedSQL = preg_replace('/^```sql\s*/i', '', $advancedSQL);
    $advancedSQL = preg_replace('/^```\s*/', '', $advancedSQL);
    $advancedSQL = preg_replace('/\s*```$/', '', $advancedSQL);

    // ---------------------------------------------------------
    // BÖLÜM 3: KAYIT
    // ---------------------------------------------------------

    $finalSQL = $structureSQL . "\n\n" .
        "-- =============================================\n" .
        "-- PART 2: BUSINESS LOGIC IMPLEMENTATION\n" .
        "-- Generated based on Business Rules & Schema\n" .
        "-- =============================================\n\n" .
        $advancedSQL;

    // Veritabanına Kaydet
    $stmtHistory = $db->prepare("INSERT INTO project_exports (project_id, sql_content) VALUES (?, ?)");
    $stmtHistory->execute([$project_id, $finalSQL]);
    $db->prepare("UPDATE projects SET status = 'completed' WHERE id = ?")->execute([$project_id]);
    echo json_encode(['success' => true, 'sql' => $finalSQL, 'message' => 'SQL Generated based on Rules & Schema.']);

} catch (Exception $e) {
    echo json_encode(['success' => false, 'message' => $e->getMessage()]);
}
?>